version: '3'

services:
  urlshortener:
    container_name: shortener
    build: .
    ports:
      - '4761:4761'
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis-data/data:/data
      - redis-data/redis.conf:/redis.conf
    restart: always

volumes:
  redis-data:
