version: '3'

services:
  urlshortener:
    container_name: shortener
    build: .
    ports:
      - '4761:4761'
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    volumes:
      - $HOME/redis:/data
    restart: always
